services:
  api:
    container_name: labdevops-back
    image: labdevops-back:latest
    ports:
      - 8002:8080
    build:
      context: .
      target: develop
    volumes:
      - .:/app

  api-production:
    container_name: labdevops-back
    image: docker.io/polirritmico/labdevops-back:latest
    ports:
      - 8002:8080
    build:
      target: production
