services:
  api:
    container_name: labdevops-front
    image: labdevops-front:latest
    ports:
      - 8002:8080
    build:
      context: .
      target: develop
    volumes:
      - .:/app

  api-production:
    container_name: labdevops-front-prod
    image: docker.io/polirritmico/labdevops-front:latest
    ports:
      - 8002:8080
    build:
      target: production
