services:
  api:
    container_name: labdevops-back
    image: labdevops-back:latest
    ports:
      - 8002:8080
    build:
      context: .
      target: develop
    volumes:
      - .:/app

  api-production:
    container_name: labdevops-back
    image: docker.io/polirritmico/labdevops-back:latest
    ports:
      - 8002:8080
    build:
      target: production
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
        reservations:
          memory: 512M
          cpus: "0.5"
